/*
 * This file is part of the Chomsky4CYK project [C4CYK].
 * Copyright (C) 1998-2026 Nicolas Darnis <ndarnis@free.fr>.
 *
 * C4CYK is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * C4CYK is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with C4CYK. If not, see <http://www.gnu.org/licenses/>. 
 */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <getopt.h>
#include <stdbool.h>

#include <gdsl.h>

#include "misc.h"
#include "rules.h"
#include "main.h"
#include "symbols.h"
#include "parser.h"
#include "objects.h"

typedef enum
{
    LG_EMPTY,
    LG_EPSILON
} langage;

/* Global variables */
gdsl_list_t X; /* Terminal symbols */
gdsl_list_t V; /* No-terminal symbols (i.e. variables) */
gdsl_list_t G; /* Rules (ie. grammar) */

static bool verbose = false;

static int* RequierementsTable = NULL; /* Requirements array */
static gdsl_2darray_t T = NULL;
static symbol* Axiom;
static object** ObjectsTable; /* Objects array */

static void grammar_write (FILE* file);
static void grammar_number (void);
static void variables_number(void);

static void build_requirements_table (void);
static void destroy_requirements_table (void);

static void build_dependency_table (void);
static void destroy_dependency_table (void);

static void build_chomsky_normal_form (FILE* out);

static void Step1 (void);
static void Step2 (void);
static void Step3 (void);
static void Step4 (void);
static void Step5 (void);

static symbol* GetAxiom (void);
static unsigned short int L (symbol* s);
static bool CYK (char* mot);

static void transitive_closure (void);
static bool leads_to (symbol* v1, symbol* v2);

static void remove_useless_variables (void);
static bool symbol_is_in_grammar (symbol* s);

static void version (void);
static void usage (void);

int main (int argc, char* argv[])
{
    FILE* input_file = NULL;
    FILE* output_file = NULL;
    
    /* 1. Reading command-line options */
    {
	int opt;
	int option_index = 0;
	
	static struct option long_options[] = 
	{
	    { "input-file",  required_argument, 0, 'i' },
	    { "output-file", required_argument, 0, 'o' },
	    { "verbose",     no_argument,       0, 'v' },
	    { "version",     no_argument,       0,  0 },
	    { "help",        no_argument,       0, 'h' },
	    { 0,             0,                 0,  0 }
	};
	
	while ((opt = getopt_long (argc, argv, "i:o:vh", long_options, &option_index)) != -1)
	{
	    if (opt == 0)
	    {
		/* long option without short equivalent */
		if (strcmp (long_options[option_index].name, "version") == 0)
		{
		    version ();
		    exit (EXIT_SUCCESS);
		}
		continue;
	    }
	    
	    switch (opt)
	    {
	    case 0:
		break;
				
	    case 'i': /* input-file */
		if (!optarg)
		{
		    usage ();
		    exit (EXIT_FAILURE);
		}
		
		input_file = fopen (optarg, "r");
	
		if (!input_file)
		{
		    printf ("Unable to open file %s.\n", optarg);
		    exit (EXIT_FAILURE);
		}
		break;

				
	    case 'o': /* output-file */
		if (!optarg)
		{
		    usage ();
		    exit (EXIT_FAILURE);
		}
		
		output_file = fopen (optarg, "w+");
		break;

	    case 'h': /* help */
		usage ();
		exit (EXIT_SUCCESS);
		break;
		
	    case 'v': /* verbose */
		verbose = true;
		break;

	    default:
		exit (EXIT_FAILURE);
	    }
	}
    }

    if (input_file == NULL)
    {
	usage ();
	exit (EXIT_FAILURE);
    }

    /* Making-of lists */
    X = gdsl_list_alloc ("X", symbol_alloc, symbol_free); /* strings_compare */
    V = gdsl_list_alloc ("V", symbol_alloc, symbol_free); /* strings_compare */
    G = gdsl_list_alloc ("G", rule_alloc, rule_free);     /* symbols_compare */
    
    /* Inserting '|' & '#' into X */
    gdsl_list_insert_head (X, "|");     
    gdsl_list_insert_head (X, "#");
    
    /* Input file parsing */
    if (yy_parse_file (input_file) != 0)
    {
	printf ("Input file is not supported.\n");
	exit (EXIT_FAILURE);
    }
    
    /* Building Chomsky normal form */
    build_chomsky_normal_form (output_file);

    /* Playing with CYK algorithm */
    {
	char word[256];
	bool done = false;
	do
	{
	    printf ("Enter a word to check if it belongs to language L(G), generated by input grammar G ('quit' to exit): ");
	    scanf ("%s", word);
	    
	    done = strcmp (word, "quit") == 0 ? true : false;
	    if (done) break;

	    /* Check if entry belongs or not to the language */
	    if (CYK (word)) printf ("The word '%s' belongs ", word);
	    else printf ("The word '%s' DOES NOT belongs ", word);
	    printf ("to L(G).\n");
	    
	} while (!done);
    }
    
    /* Cleanup */
    gdsl_list_free (X);
    gdsl_list_free (V);
    gdsl_list_free (G);
    
    if (T != NULL)
    {
	gdsl_2darray_free (T);
    }
    
    if (input_file)
    {
	fclose (input_file);
    }

    if (output_file)
    {
	fclose (output_file);
    }
    
    exit (EXIT_SUCCESS);
}

/****************************************************************************/

static void grammar_write (FILE* file)
{
    bool new_line = true;
    gdsl_list_write (G, rule_write, (file == NULL) ? stdout : file, (void*) &new_line);
}

static void grammar_number (void)
{
    unsigned long int n = 0;
    
    gdsl_list_cursor_t cg = gdsl_list_cursor_alloc (G);
    for (gdsl_list_cursor_move_to_head (cg); gdsl_list_cursor_get_content (cg); gdsl_list_cursor_step_forward (cg))
    {
	rule* r = (rule*) gdsl_list_cursor_get_content (cg);
	rule_set_num (r, ++n);
    }
    
    gdsl_list_cursor_free (cg);
}

static void variables_number (void)
{
    unsigned long int n = 0;
    
    gdsl_list_cursor_t cv = gdsl_list_cursor_alloc (V);
    for (gdsl_list_cursor_move_to_head (cv); gdsl_list_cursor_get_content (cv); gdsl_list_cursor_step_forward (cv))
    {
	symbol* s = (symbol*) gdsl_list_cursor_get_content (cv);
	symbol_set_num (s, ++n);
    }
    
    gdsl_list_cursor_free (cv);
}

static void build_requirements_table (void)
{
    gdsl_list_cursor_t cv = NULL, cg = NULL;
    gdsl_list_t usable_objects = gdsl_list_alloc ("UO", NULL, NULL);
    gdsl_list_t processed_objects = gdsl_list_alloc ("TO", NULL, NULL);
    unsigned long int i = 0;
    unsigned long int nb_rules = gdsl_list_get_size (G);
    unsigned long int nb_variables = gdsl_list_get_size (V);
    unsigned long int n = 1 + nb_rules + nb_variables;
    symbol* X;
    rule* P;
    
    /**********************************************************************************/
    /* RequierementsTable & usable_objects initialisations                            */
    /**********************************************************************************/
    
    grammar_number ();
    variables_number ();
    build_dependency_table ();
    
#ifdef DEBUG
    {
	bool new_line = false;
	printf ("*******************************************\n");
	gdsl_list_dump (G, rule_write, stdout, &new_line);
	printf ("*******************************************\n");
    }
#endif
    
    RequierementsTable = (int*) malloc (n * sizeof (int));
    
    /* RequierementsTable array init by variables... */
    cv = gdsl_list_cursor_alloc (V);
    for (i = 0, gdsl_list_cursor_move_to_head (cv); (X = (symbol*) gdsl_list_cursor_get_content (cv)); gdsl_list_cursor_step_forward (cv))
    {
	/* WARNING: HERE, WE MUST ABSOLUTELY HAVE i == champ num de gdsl_list_cursor_get_content (cursor) */
	assert (++i == symbol_get_num (X)); 
	RequierementsTable[i] = 1; 
    }
    gdsl_list_cursor_free (cv);
    
    /* ...then, by rules */
    cg = gdsl_list_cursor_alloc (G);
    for (gdsl_list_cursor_move_to_head (cg); (P = (rule*) gdsl_list_cursor_get_content (cg)); gdsl_list_cursor_step_forward (cg))
    {
	int lg = rule_get_right_member_length (P);
	
	/* WARNING: HERE, WE MUST ABSOLUTELY HAVE i == r->num + nb_variables */
	assert (++i == nb_variables + rule_get_num (P));
	RequierementsTable[i] = lg;
	
	if (lg <= 0)
	{
	    object* o = ObjectsTable[i];
	    gdsl_list_insert_tail (usable_objects, (void*) o);
	}
    }
    gdsl_list_cursor_free (cg);
    
#ifdef DEBUG
    gdsl_list_dump (usable_objects, NULL, stdout, NULL);
#endif
    
    /**********************************************************************************/
    /* RequierementsTable building algorithm                                          */
    /**********************************************************************************/
    
    while (!gdsl_list_is_empty (usable_objects))
    {
	object* alpha;
	gdsl_list_t lalpha;
	
	alpha = (object*) gdsl_list_get_head (usable_objects);
	
	lalpha = object_get_list (alpha);
	
	gdsl_list_delete_head (usable_objects);
	
	if (!gdsl_list_search (processed_objects, NULL, alpha))
	{
	    unsigned long int* k;
	    gdsl_list_insert_head (processed_objects, alpha);
	    
	    gdsl_list_cursor_t ca = gdsl_list_cursor_alloc (lalpha);
	    for (gdsl_list_cursor_move_to_head (ca); (k = gdsl_list_cursor_get_content (ca)); gdsl_list_cursor_step_forward (ca))
	    {
		unsigned long int K = *k;
		
		switch (object_get_type (alpha))
		{
		case OT_RULE:
		{
		    object* beta = ObjectsTable[K];
		    RequierementsTable[object_get_num (beta)] = RequierementsTable[object_get_num (beta)] - 1;
		    
		    if (RequierementsTable[object_get_num (beta)] <= 0)
		    {
			gdsl_list_insert_tail (usable_objects, beta);
		    }
		}
		break;
		
		case OT_VARIABLE:
		{
		    rule* r;
		    object* beta;
		    
		    /*assert (K <= gdsl_list_get_size (G));*/
		    assert (*k <= gdsl_list_get_size (G));
		    
		    r = (rule*) gdsl_list_search_by_position (G, K - 1);
		    assert (r != NULL); /* Can't be NULL ! */
		    
		    beta = ObjectsTable[rule_get_num (r) + nb_variables];
		    RequierementsTable[object_get_num (beta) + nb_variables] = RequierementsTable[object_get_num (beta) + nb_variables] - 1;
		    
		    if (RequierementsTable[object_get_num (beta) + nb_variables] <= 0)
		    {
			gdsl_list_insert_tail (usable_objects, beta);
		    }
		}
		break;
		}
	    }
	    gdsl_list_cursor_free (ca);
	}
    }
    
    /**********************************************************************************/
    /* END                                                                            */
    /**********************************************************************************/
    
    destroy_dependency_table ();
    gdsl_list_free (usable_objects);
    gdsl_list_free (processed_objects);
}

static void destroy_requirements_table (void)
{
    if (RequierementsTable != NULL)
    {
	free (RequierementsTable);
    }
}

static void build_dependency_table (void)
{
    gdsl_list_cursor_t cv, cg;
    unsigned long int nb_variables = gdsl_list_get_size (V);
    unsigned long int nb_rules = gdsl_list_get_size (G);
    unsigned long int n = 1 + nb_rules + nb_variables;
    unsigned long int i = 0;
    
    ObjectsTable = (object**) malloc (n * sizeof (object*));
    
    /* Variables */
    cv = gdsl_list_cursor_alloc (V);
    for (gdsl_list_cursor_move_to_head (cv); gdsl_list_cursor_get_content (cv); gdsl_list_cursor_step_forward (cv))
    {
	symbol*s = (symbol*) gdsl_list_cursor_get_content (cv);
	object* o = object_alloc (OT_VARIABLE, (void*) s);
	gdsl_list_t lo = object_get_list (o);
	
	assert (++i == symbol_get_num (s));
	
	gdsl_list_cursor_t cg = gdsl_list_cursor_alloc (G);
	for (gdsl_list_cursor_move_to_head (cg); gdsl_list_cursor_get_content (cg); gdsl_list_cursor_step_forward (cg))
	{
	    rule* r = (rule*) gdsl_list_cursor_get_content (cg);
	    gdsl_list_t ls = rule_get_production (r);
	    gdsl_list_cursor_t cls = gdsl_list_cursor_alloc (ls);
	    for (gdsl_list_cursor_move_to_head (cls); gdsl_list_cursor_get_content (cls); gdsl_list_cursor_step_forward (cls))
	    {
		symbol* sr = (symbol*) gdsl_list_cursor_get_content (cls);
		unsigned long int k = rule_get_num (r);
		
		if (symbol_names_compare (sr, s) == 0)
		{
		    gdsl_list_insert_tail (lo, (void*) &k);
		}
	    }
	    gdsl_list_cursor_free (cls);
	}
	gdsl_list_cursor_free (cg);
	
	ObjectsTable[i] = o;
    }
    gdsl_list_cursor_free (cv);
    
    /* Rules */
    cg = gdsl_list_cursor_alloc (G);
    for (gdsl_list_cursor_move_to_head (cg); gdsl_list_cursor_get_content (cg); gdsl_list_cursor_step_forward (cg))
    {
	rule* r = (rule*) gdsl_list_cursor_get_content (cg);
	object* o = object_alloc (OT_RULE, (void*) r);
	gdsl_list_t lo = object_get_list (o);
	symbol* s = rule_get_symbol (r);
	unsigned long int k = symbol_get_num (s);
	
	assert (++i == nb_variables + rule_get_num (r));
	
	if (symbol_is_variable (s))
	{
	    gdsl_list_insert_tail (lo, (void*) &k);
	}
	
	ObjectsTable[i] = o;
    }
    gdsl_list_cursor_free (cg);
}

static void destroy_dependency_table (void)
{
    unsigned long int i;
    unsigned long int n = 1 + gdsl_list_get_size (G) + gdsl_list_get_size (V);
    
    for (i = 1; i < n; i++)
    {
	object_free (ObjectsTable[i]);
    }
    
    free (ObjectsTable);
}

/* Main algorithm: building of Chomsky normal form */

static void build_chomsky_normal_form (FILE* out)
{
    if (verbose)
    {
	printf ("INPUT GRAMMAR G:\n");
	grammar_write (stdout);
	printf ("\n");
    }
       
    Step1 ();
    Step2 ();
    Step3 ();
    Step4 ();
    Step5 ();
    
    if (verbose)
    {
	printf ("\nGRAMMAR G IN CHOMSKY NORMAL FORM:\n");
	grammar_number ();
	grammar_write (stdout);
	printf ("\n");
    }

    if (out)
    {
	grammar_write (out);
    }
}

/******************************************************************************/
/* STEP 1: Union removal                                                      */
/******************************************************************************/

static void Step1 (void)
{
    rule* r;
    gdsl_list_cursor_t cg = gdsl_list_cursor_alloc (G);
    
    /* For each rule r, we check its production part p */
    for (gdsl_list_cursor_move_to_head (cg); (r = (rule*) gdsl_list_cursor_get_content (cg)); gdsl_list_cursor_step_forward (cg))
    {
	symbol* sp;
	gdsl_list_t p = rule_get_production (r); /* p is r's production */
	
	/* For each p's symbol (sp), we check if its union */
	gdsl_list_cursor_t cp = gdsl_list_cursor_alloc (p);
	gdsl_list_cursor_move_to_head (cp);
	while ((sp = (symbol *) gdsl_list_cursor_get_content (cp))) /* sp is p's symbol */
	{
	    if (symbol_is_union (sp))
	    {
		symbol* sg;
		rule* tmp = (rule*) gdsl_list_cursor_insert_after (cg, (void*) rule_get_symbol (r));
		gdsl_list_t l = rule_get_production (tmp);

		gdsl_list_cursor_delete (cp); /* NOTE 1: WARNING: curor is moved AFTER deleted element !!!
                                               * So, we *MUST NOT* call gdsl_list_cursor_step_forward (cp);
					       * (check GDSL's manual).
					       */

		while ((sg = (symbol *) gdsl_list_cursor_get_content (cp)) && !symbol_is_union (sg))
		{
		    gdsl_list_insert_tail (l, sg);
		    gdsl_list_cursor_delete (cp);
		    /* FORBIDDEN: gdsl_list_cursor_step_forward (cp); cf. NOTE 1 */
		}
	    }
	    else
	    {
		/* Here it's okay because we have not deleted cursor, cf. NOTE 1 */
		gdsl_list_cursor_step_forward (cp);
	    }
	}
	gdsl_list_cursor_free (cp);
    }
    gdsl_list_cursor_free (cg);

#ifdef DEBUG
    if (verbose)
    {
	printf ("****** STEP 1 ******\n");
	grammar_write (stdout);
	printf ("*********************\n");
    }
#endif
}

/*************************************************************************************************************************/
/* STEP 2: Transformation du membre droit de chaque règle en une lettre ou en une concaténation de non terminaux         */
/*************************************************************************************************************************/

static void Step2 (void)
{
    rule *r;
    gdsl_list_cursor_t cg = gdsl_list_cursor_alloc (G);
    
    for (gdsl_list_cursor_move_to_head (cg); (r = (rule *) gdsl_list_cursor_get_content (cg)); gdsl_list_cursor_step_forward (cg))
    {
	gdsl_list_cursor_t cp = NULL;
	gdsl_list_t prod = rule_get_production (r);
	symbol *sp;
	symbol *sr = rule_get_symbol (r);
	char *symbol_name = symbol_get_name (sr);
	
	if (symbol_name[1] == '_') continue;
	
	cp = gdsl_list_cursor_alloc (prod);
	for (gdsl_list_cursor_move_to_head (cp); (sp = (symbol *) gdsl_list_cursor_get_content (cp)); gdsl_list_cursor_step_forward (cp))
	{
	    if (symbol_is_terminal (sp))
	    {
		symbol *s;
		char *chaine; 
		int bytes_nb = 3 + strlen (symbol_get_name (sp));
		
		chaine = (char *) malloc (bytes_nb);
		snprintf (chaine, bytes_nb, "V_%s", symbol_get_name (sp));
		
		if (!(s = (symbol *) gdsl_list_search (V, strings_compare, (void *) chaine)))
		{
		    gdsl_list_t l;
		    rule *tmp;
		    s = (symbol*) gdsl_list_insert_tail (V, (void*) chaine);
		    tmp = (rule*) gdsl_list_insert_tail (G, s);
		    l = rule_get_production (tmp);
		    gdsl_list_insert_tail (l, (void*) sp); 
		}
		gdsl_list_cursor_set_content (cp, s);
		free (chaine);
	    }
	}
	gdsl_list_cursor_free (cp);
    }
    gdsl_list_cursor_free (cg);

#ifdef DEBUG
    if (verbose)
    {
	printf ("\n****** STEP 2 ******\n");
	grammar_write (stdout);
	printf ("*********************\n");
    }
#endif
}

/*************************************************************************************************************************/
/* STEP 3: Removing of too-long right members (who have length > 2)                                                      */
/*************************************************************************************************************************/

static void Step3 (void)
{
    int i = 1;
    rule *r;
    
    gdsl_list_cursor_t cg = gdsl_list_cursor_alloc (G);
    for (gdsl_list_cursor_move_to_head (cg); (r = (rule *) gdsl_list_cursor_get_content (cg)); gdsl_list_cursor_step_forward (cg))
    {
	gdsl_list_t prod = rule_get_production (r);
        gdsl_list_cursor_t cp = NULL;
	
	if (gdsl_list_get_size (prod) <= 2) continue;

	cp = gdsl_list_cursor_alloc (prod);
	for (gdsl_list_cursor_move_to_head (cp), gdsl_list_cursor_step_forward (cp); gdsl_list_cursor_get_content (cp); gdsl_list_cursor_step_forward (cp))
	{
	    if (gdsl_list_cursor_has_succ (cp))
	    {
	      gdsl_list_t l; 
	      rule *tmp;
	      symbol *s;
	      char *chaine;
	      void *x;

	      chaine = (char *) malloc (5); 
	      snprintf (chaine, 5, "N_%02d", i++);
	      s = (symbol *) gdsl_list_insert_tail (V, (void *) chaine);
	      free (chaine);
	      
	      tmp = (rule *) gdsl_list_cursor_insert_after (cg, (void *) s);
	      l = rule_get_production (tmp);
	      
	      while ((x = gdsl_list_cursor_get_content (cp)))
	      {		  
		  gdsl_list_insert_tail (l, (void *) x);
		  gdsl_list_cursor_delete (cp);
		  /*gdsl_list_cursor_step_forward (cp); cf. NOTE 1 */
	      }

	      gdsl_list_insert_tail (prod, (void *) gdsl_list_get_tail (V));
	    }
 	}
	gdsl_list_cursor_free (cp);
    }
    gdsl_list_cursor_free (cg);

#ifdef DEBUB
  if (verbose)
    {
      printf ("\n****** STEP 3 ******\n");
      grammar_write (stdout);
      printf ( "*********************\n");
    }
  #endif
}

/*************************************************************************************************************************/
/* STEP 4: elimination of the maximum number of empty words.                                                             */
/*************************************************************************************************************************/

static void Step4 (void)
{
    rule *r;
    rule *rg;
    char *axiome = symbol_get_name (GetAxiom ()); /* WARNING: DO NOT MOVE ! */
    symbol *x;
    gdsl_list_cursor_t cv = NULL;
    gdsl_list_cursor_t cg = NULL;
    
    /* a) Ajout des nouveaux symboles non-terminaux X~ et X# à V et introduction des nouvelles règles X -> X~ et X -> X# dans G */
    cv = gdsl_list_cursor_alloc (V);
    cg = gdsl_list_cursor_alloc (G);
    
    for (gdsl_list_cursor_move_to_tail (cg), gdsl_list_cursor_move_to_head (cv); gdsl_list_cursor_get_content (cv); gdsl_list_cursor_step_forward (cv))
    { 
	gdsl_list_t actu;
	symbol *v;
	symbol *symb = (symbol *) gdsl_list_cursor_get_content (cv);
	char *chaine;
	
	chaine = (char *) malloc (2 + strlen (symbol_get_name (symb)));
	sprintf (chaine, "%s%c", symbol_get_name (symb), SYMB_PLUS);
	
	v = (symbol *) gdsl_list_insert_head (V, (void *) chaine);
	r = (rule *)gdsl_list_insert_tail (G, (void *) symb);
	actu = rule_get_production (r);
	gdsl_list_insert_head (actu, v);
	free (chaine);
	
	chaine = (char *) malloc (2 + strlen (symbol_get_name (symb))); 
	sprintf (chaine, "%s%c", symbol_get_name (symb), SYMB_EPSILON);
	
	v = (symbol *) gdsl_list_insert_head (V, chaine);
	r = (rule *) gdsl_list_insert_tail (G, (void *) symb);
	actu = rule_get_production (r);
	gdsl_list_insert_head (actu, v);
	free (chaine);
    }

#ifdef DEBUG
    if (verbose)
    {
	printf ("\n****** STEP 4 ******\n");
	printf ("a)\n");
	grammar_write (stdout);
    }
#endif
    
    /* b) Rules modifications */
    for ( ; (rg = (rule*) gdsl_list_cursor_get_content (cg)); gdsl_list_cursor_step_backward (cg))
    {
	symbol* rs = rule_get_symbol (rg);
	symbol* symb = NULL;
	char* chaine = (char *) symbol_get_name (rs);
	gdsl_list_t actu = rule_get_production (rg);
	gdsl_list_cursor_t ca = gdsl_list_cursor_alloc (actu);

	symb = (symbol*) gdsl_list_cursor_get_content (ca);
	gdsl_list_cursor_move_to_head (ca);
	
	/* Modification of kind X -> c : X~ -> c */
	if (symbol_is_terminal (symb)) 
	{
	    char* mot = (char*) malloc (2 + strlen (chaine));
	    sprintf (mot, "%s%c", chaine, SYMB_PLUS);	  
	    rule_set_symbol (rg, (symbol*) gdsl_list_search (V, strings_compare, (void*) mot));
	    free (mot);
	    continue;
	}

	/* Modification of kind X -> # : X# -> # */
	if (symbol_is_epsilon (symb)) 
	{
	    char* mot = (char*) malloc (2 + strlen (chaine));
	    sprintf (mot, "%s%c", chaine, SYMB_EPSILON);
	    rule_set_symbol (rg, gdsl_list_search (V, strings_compare, (void*) mot));

	    free (mot);
	    continue;
	}

	/* Modification of kind X -> Y : X~ -> Y~ and X# -> Y# */
	if (!gdsl_list_cursor_has_succ (ca)) 
	{		  
	    symbol *vc1, *vc2;
	    char *mot1, *mot2;
	    gdsl_list_t actu2;

	    mot1 = (char *) malloc (2 + strlen (chaine)); 
	    sprintf (mot1, "%s%c", chaine, SYMB_PLUS); 
	    mot2 = (char *) malloc (2 + strlen (symbol_get_name (symb))); 
	    sprintf (mot2, "%s%c", symbol_get_name (symb), SYMB_PLUS); 
	    
	    if ((vc1 = (symbol *) gdsl_list_search (V, strings_compare, (void *) mot1)))
	    {
		rule_set_symbol (rg, vc1);
	    }
	    
	    if ((vc2 = (symbol *) gdsl_list_search (V, strings_compare, (void *) mot2)))
	    {
		gdsl_list_cursor_set_content (ca, vc2);
	    }
	    
	    free (mot1);
	    free (mot2);
	    
	    mot1 = (char *) malloc (2 + strlen (chaine)); 
	    sprintf (mot1, "%s#", chaine); 
	    mot2 = (char *) malloc (2 + strlen (symbol_get_name (symb))); 
	    sprintf (mot2, "%s#", symbol_get_name (symb)); 
	    
	    if ((vc1 = gdsl_list_search (V, strings_compare, (void *) mot1)))
	    {
		r = (rule *) gdsl_list_cursor_insert_after (cg, vc1);
		actu2 = rule_get_production (r);
	    }
	    
	    if ((vc2 = gdsl_list_search (V, strings_compare, (void *) mot2)))
		gdsl_list_insert_tail (actu2, vc2);
	    
	    continue;
	}

	/* Modification of kind X -> Y Z : X~ -> Y~ Z~, X~ -> Y~ Z#, X~ -> Y# Z~ and X# -> Y# Z# */
	{
	    symbol *vc, *vc0, *vc1, *vc2;
	    char *mot1, *mot2;
	    symbol *as;
	    rule *cg2, *cg3, *cg4;
	    gdsl_list_t actu2, actu3, actu4;
	    
	    mot1 = (char *) malloc (2 + strlen (chaine)); 
	    sprintf( mot1, "%s%c", chaine, SYMB_PLUS); 
	    mot2 = (char *) malloc (2 + strlen (chaine)); 
	    sprintf (mot2, "%s%c", chaine, SYMB_EPSILON); 
	    
	    if ((vc = (symbol *) gdsl_list_search (V, strings_compare, (void *) mot1)))
	    {
		rule_set_symbol (rg, vc);
	    }
	    
	    vc0 = (symbol *) gdsl_list_search (V, strings_compare, (void *) mot2);
	    
	    /* Insertion des 3 NT dans G avec X qui donne X~ X~ X# */
	    cg2 = (rule *) gdsl_list_cursor_insert_after (cg, (void *) vc); 
	    actu2 = rule_get_production (cg2);
	    
	    cg3 = (rule *) gdsl_list_cursor_insert_after (cg, (void *) vc); 
	    actu3 = rule_get_production (cg3);
	    
	    cg4 = (rule *)gdsl_list_cursor_insert_after (cg, (void *) vc0); 
	    actu4 = rule_get_production (cg4);
	    
	    free (mot1);
	    free (mot2);
	    
	    /* Update of first element into the 4 lists */
	    mot1 = (char *) malloc (2 + strlen (symbol_get_name (symb)));
	    mot2 = (char *) malloc (2 + strlen (symbol_get_name (symb)));
	    sprintf (mot1, "%s%c", symbol_get_name (symb), SYMB_PLUS); 
	    sprintf (mot2, "%s%c", symbol_get_name (symb), SYMB_EPSILON); 
	    vc1 = gdsl_list_search (V, strings_compare, (void *) mot1);
	    vc2 = gdsl_list_search (V, strings_compare, (void *) mot2);
	    
	    gdsl_list_cursor_set_content (ca, vc1);
	    gdsl_list_insert_tail (actu2, vc1);
	    gdsl_list_insert_tail (actu3, vc2);
	    gdsl_list_insert_tail (actu4, vc2);
	    gdsl_list_cursor_step_forward (ca);
	    
	    free (mot1);
	    free (mot2);
	    
	    /* Update of second element into the 4 lists */
	    as = (symbol *) gdsl_list_cursor_get_content (ca);
	    mot1 = (char *) malloc (2 + strlen (symbol_get_name (symb)));
	    mot2 = (char *) malloc (2 + strlen (symbol_get_name (symb))); 
	    
	    sprintf (mot1, "%s%c", symbol_get_name (as), SYMB_PLUS ); 
	    sprintf (mot2, "%s%c", symbol_get_name (as), SYMB_EPSILON); 
	    
	    vc1 = (symbol *) gdsl_list_search ( V, strings_compare, (void *) mot1);
	    vc2 = (symbol *) gdsl_list_search ( V, strings_compare, (void *) mot2);
	    
	    gdsl_list_cursor_set_content (ca, (void *) vc1);
	    gdsl_list_insert_tail (actu2, (void *) vc2);
	    gdsl_list_insert_tail (actu3, (void *) vc1);
	    gdsl_list_insert_tail (actu4, (void *) vc2); 
	    
	    free (mot1);
	    free (mot2); 
	}
	gdsl_list_cursor_free (ca);
    }

#ifdef DEBUG
    if (verbose)
    {
	printf ("b)\n");
	grammar_write (stdout);
    }
#endif
    
    /* c) Removing of initials variables X except axiom */
    gdsl_list_cursor_move_to_head (cg);
    while ( (r = (rule *) gdsl_list_cursor_get_content (cg)) /*!gdsl_list_cursor_is_on_tail (cg)*/)
    {
	symbol *s = rule_get_symbol (r);
	char *ns = NULL;
	int lg = strlen (axiome);

	ns = symbol_get_name (s);

	/* We do not process axiom */
	if (strncmp (axiome, ns, lg) == 0)
	{
	    gdsl_list_cursor_step_forward (cg);
	    continue;
	}

	/* Symbol s is not initial variable */
	if (!symbol_is_initial (s))
	{
	    gdsl_list_cursor_step_forward (cg);
	    continue;
	}

	/* Symbol s IS an initial variabl, so it must be removed */
	gdsl_list_cursor_delete (cg); /* cf. NOTE 1 */
    }

    /* Removing useless variables into V */
    remove_useless_variables ();

#ifdef DEBUG
    if (verbose)
    {
	printf ("c)\n");
	grammar_write (stdout);
    }
#endif
    
    /* d) */
    build_requirements_table ();

    for (gdsl_list_cursor_move_to_head (cv); (x = (symbol *) gdsl_list_cursor_get_content (cv)); gdsl_list_cursor_step_forward (cv))
    {
	symbol *X0;
	char *symbol_name = symbol_get_name (x);
	unsigned long int n = strlen (symbol_name);
	
	if (symbol_name[n-1] != '#')
	{
	    continue;
	}
	
	X0 = gdsl_list_search (V, strings_compare, (char*) symbol_name);
	
	switch (L (X0))
	{
	case LG_EMPTY:
	{
	    rule *r;
	    
	    gdsl_list_cursor_move_to_head (cg);
	    while ((r = (rule *) gdsl_list_cursor_get_content (cg)))
	    {
		gdsl_list_t l = rule_get_production (r);
		symbol *s1, *s2 = NULL;
		
		s1 = (symbol *) gdsl_list_get_head (l);
		
		if (gdsl_list_get_size (l) == 2)
		{
		    s2 = (symbol *) gdsl_list_get_tail (l);
		}
		
		if (symbol_names_compare (X0, s1) == 0)
		{
		    gdsl_list_cursor_delete (cg); /* cf. NOTE 1 */
		    continue;
		}
		
		if (s2 != NULL)
		{
		    if (symbol_names_compare (X0, s2) == 0)
		    {
			gdsl_list_cursor_delete (cg);  /* cf. NOTE 1 */
			continue;
		    }
		}
		
		gdsl_list_cursor_step_forward (cg);
	    }
	}
	break;
	
	case LG_EPSILON:
	{
	    rule* r;
	    
	    gdsl_list_cursor_move_to_head (cg);
	    while ((r = (rule*) gdsl_list_cursor_get_content (cg)))
	    {
		gdsl_list_t l = rule_get_production (r);
		symbol* s1 = (symbol*) gdsl_list_get_head (l);
		symbol* s2 = NULL;
		char* symbol_name = symbol_get_name (s1);
		unsigned long int n = strlen (symbol_name);
		
		if (gdsl_list_get_size (l) == 1)
		{
		    if (symbol_name[n-1] == '#')
		    {
			symbol* epsilon = (symbol*) gdsl_list_search (X, strings_compare, (void *) "#");
			gdsl_list_delete_head (l);
			gdsl_list_insert_head (l, (void *) epsilon);
			gdsl_list_cursor_step_forward (cg);
			continue;
		    }
		    else
		    {
			if (symbol_names_compare (X0, s1) == 0)
			{
			    gdsl_list_cursor_delete (cg); /* cf. NOTE 1 */
			    continue;
			}
		    }
		}
		else
		{
		    s2 = (symbol*) gdsl_list_get_tail (l);
		    
		    if (symbol_names_compare (X0, s1) == 0)
		    {
			gdsl_list_delete_head (l);
		    }
		    
		    if (symbol_names_compare (X0, s2) == 0)
		    {
			gdsl_list_delete_tail (l);
		    }
		    
		    if (gdsl_list_get_size (l) == 0)
		    {
			gdsl_list_cursor_delete (cg); /* cf. NOTE 1 */
			continue;
		    }
		}

		gdsl_list_cursor_step_forward (cg);
	    }
	}
	break;
	}
    }
    
    /* Removing of rules of kind X# -> ... left */
    gdsl_list_cursor_move_to_head (cg);
    while ((r = (rule *) gdsl_list_cursor_get_content (cg)))
    {
	symbol* s = rule_get_symbol (r);
	char* symbol_name = symbol_get_name (s);
	unsigned long int n = strlen (symbol_name);
	
	if (symbol_name[n-1] == SYMB_EPSILON)
	{
	    gdsl_list_cursor_delete (cg);  /* cf. NOTE 1 */
	    continue;
	}
	
	gdsl_list_cursor_step_forward (cg);
    }
    
    destroy_requirements_table ();
    
    /* Removing of useless non-terminal from V */
    remove_useless_variables ();
    
    gdsl_list_cursor_free (cv);
    gdsl_list_cursor_free (cg);

#ifdef DEBUG
    if (verbose)
    {
	printf ("d)\n");
	grammar_number ();
	grammar_write (stdout);
	printf ("*********************\n");
    }
#endif
}

/*************************************************************************************************************************/
/* STEP 5: Removing unitary rules                                                                                        */
/*************************************************************************************************************************/

static void Step5 (void)
{
    gdsl_list_cursor_t cg = NULL;
    gdsl_list_t tmp0, tmp1, tmp2;
    rule* r;
    
    tmp0 = gdsl_list_alloc (NULL, NULL, NULL);
    tmp1 = gdsl_list_alloc (NULL, NULL, NULL);
    tmp2 = gdsl_list_alloc (NULL, NULL, NULL);
    
    grammar_number ();
    variables_number ();
    
    /* Build of T, the transitive closure of graph belonging to relation -> */
    transitive_closure ();

    /* 1) For each rule X -> c */
    cg = gdsl_list_cursor_alloc (G);
    for (gdsl_list_cursor_move_to_head (cg); (r = (rule*) gdsl_list_cursor_get_content (cg)); gdsl_list_cursor_step_forward (cg))
    {
	symbol* c;
	symbol* X = rule_get_symbol (r);
	gdsl_list_t l = rule_get_production (r);
	gdsl_list_cursor_t cv = NULL;
	
	if (gdsl_list_get_size (l) != 1)
	{
	    continue;
	}
	
	c = (symbol*) gdsl_list_get_head (l);
	if (!c)
	{
	    continue;
	}
	
	if (!symbol_is_terminal (c))
	{
	    continue;
	}
	
	/* We've got a rule X -> c */
	cv = gdsl_list_cursor_alloc (V);
	for (gdsl_list_cursor_move_to_head (cv); gdsl_list_cursor_get_content (cv); gdsl_list_cursor_step_forward (cv))
	{
	    symbol* X0 = (symbol*) gdsl_list_cursor_get_content (cv);
	    
	    if (leads_to (X0, X) && symbol_get_num (X0) != symbol_get_num (X)) /* Adding of rule X0 -> c into G */
	    {
		rule* tmp = (rule*) gdsl_list_cursor_insert_before (cg, (void*) X0);
		gdsl_list_t ltmp = rule_get_production (tmp);
	      gdsl_list_insert_tail (ltmp, (void*) c);
	    }
	}
	gdsl_list_cursor_free (cv);
    }
    
    /* 2) For each rule X -> YZ */
    for (gdsl_list_cursor_move_to_head (cg); (r = (rule*) gdsl_list_cursor_get_content (cg)); gdsl_list_cursor_step_forward (cg))
    {
	gdsl_list_t l = rule_get_production (r);
	symbol* X = rule_get_symbol (r);
	symbol* Y;
	symbol* Z;
	
	if (gdsl_list_get_size (l) == 2) /* We've got a rule X -> YZ */
	{
	    gdsl_list_cursor_t ct0, cv = gdsl_list_cursor_alloc (V);
	    
	    Y = (symbol*) gdsl_list_get_head (l);
	    Z = (symbol*) gdsl_list_get_tail (l);
	    
	    for (gdsl_list_cursor_move_to_head (cv); gdsl_list_cursor_get_content (cv); gdsl_list_cursor_step_forward (cv))
	    {
	      symbol* X0 = (symbol*) gdsl_list_cursor_get_content (cv);
	      
	      if (leads_to (X0, X)) gdsl_list_insert_tail (tmp0, (void*) X0);
	      if (leads_to (Y, X0)) gdsl_list_insert_tail (tmp1, (void*) X0);
	      if (leads_to (Z, X0)) gdsl_list_insert_tail (tmp2, (void*) X0 );
	    }

	    /* Produit cartésien des listes tmp0, tmp1, tmp2 */
	    ct0 = gdsl_list_cursor_alloc (tmp0);
	    for (gdsl_list_cursor_move_to_head (ct0); gdsl_list_cursor_get_content (ct0); gdsl_list_cursor_step_forward (ct0))
	    {
		gdsl_list_cursor_t ct1 = gdsl_list_cursor_alloc (tmp1);
		for (gdsl_list_cursor_move_to_head (ct1); gdsl_list_cursor_get_content (ct1); gdsl_list_cursor_step_forward (ct1))
		{
		    gdsl_list_cursor_t ct2 = gdsl_list_cursor_alloc (tmp2);
		    for (gdsl_list_cursor_move_to_head (ct2 ); gdsl_list_cursor_get_content (ct2); gdsl_list_cursor_step_forward (ct2))
		    {
		      symbol* s0 = (symbol*) gdsl_list_cursor_get_content (ct0);
		      symbol* s1 = (symbol*) gdsl_list_cursor_get_content (ct1);
		      symbol* s2 = (symbol*) gdsl_list_cursor_get_content (ct2);
		      rule* r0;
		      gdsl_list_t l0;
		      
		      if (symbol_names_compare (X, s0) == 0 && symbol_names_compare (Y, s1) == 0 && symbol_names_compare (Z, s2) == 0)
		      {
			  continue; /* Avoid of adding rule X -> YZ twice */
		      }

		      r0 = (rule *) gdsl_list_cursor_insert_after (cg, (void*) s0);
		      gdsl_list_cursor_step_forward (cg);
		      l0 = rule_get_production (r0);
		      gdsl_list_insert_tail (l0, (void*) s1);
		      gdsl_list_insert_tail (l0, (void*) s2);
		    }
		    gdsl_list_cursor_free (ct2);
		}
		gdsl_list_cursor_free (ct1);
	    }
	    gdsl_list_cursor_free (ct0);
	    gdsl_list_cursor_free (cv);
	    
	  gdsl_list_flush (tmp0);
	  gdsl_list_flush (tmp1);
	  gdsl_list_flush (tmp2);
	}
    }

    /* 3) Removing of unitary rules */
    gdsl_list_cursor_move_to_head (cg);
    while ((r = (rule *) gdsl_list_cursor_get_content (cg)))
    {
	gdsl_list_t l = rule_get_production (r);
	symbol* Y;

	if (gdsl_list_get_size (l) != 1)
	{
	    gdsl_list_cursor_step_forward (cg);
	    continue;
	}
	
	Y = (symbol*) gdsl_list_get_head (l);
	if (!symbol_is_variable (Y))
	{
	    gdsl_list_cursor_step_forward (cg);
	    continue;
	}
	
	gdsl_list_cursor_delete (cg); /* cf. NOTE 1 */
    }
    
    gdsl_list_cursor_free (cg);
    
    gdsl_list_free (tmp0);
    gdsl_list_free (tmp1);
    gdsl_list_free (tmp2);
}

static symbol* GetAxiom (void)
{
    Axiom = (symbol*) gdsl_list_get_head (V);
    return Axiom;
}

static unsigned short int L (symbol* s)
{
    unsigned long int n = symbol_get_num (s);
    return (RequierementsTable[n] == 0) ? LG_EPSILON : LG_EMPTY;
}  

/* CYK Algorithm */

static bool CYK (char* word)
{
    bool result = false;
    int False = false, True = true;
    int i, j, k, n;
    unsigned long int card_v;
    gdsl_2darray_t* M;
    gdsl_list_cursor_t cv;
    
    grammar_number ();
    variables_number ();
    
    /* First, we check if all w_i belongs to X */
    n = strlen (word);
    for (i = 0; i < n; i++)
    {
	char c[2];
	c[0] = word[i];
	c[1] = '\0';
	
	if (gdsl_list_search (X, strings_compare, (void*) c) == NULL)
	{
	    if (verbose)
	    {
		printf ("*** Error: the %d%s letter ('%c') of input word '%s' is *NOT* defined into X set definition of input grammar G.\n", i+1, i+1==1?"-st":"-th", word[i], word);
	    }
	    
	    return false;
	}
    }
    
    card_v = gdsl_list_get_size (V);
    M = (gdsl_2darray_t*) malloc ((1 + n) * sizeof (gdsl_2darray_t));
    for (i = 1; i <= n; i++) M[i] = gdsl_2darray_alloc (NULL, n + 1, card_v + 1, number_alloc, number_free);
    
    /* Initialisation of matrix M */
    cv = gdsl_list_cursor_alloc (V);
    for (gdsl_list_cursor_move_to_head (cv); gdsl_list_cursor_get_content (cv); gdsl_list_cursor_step_forward (cv))
    {
	symbol* X = (symbol*) gdsl_list_cursor_get_content (cv);
	
	for (i = 1; i <= n; i++)
	{
	    for (k = i; k <= n; k++)
	    {
		gdsl_2darray_set_content (M[i], k, symbol_get_num (X), (void *) &False);
	    }
	}
	
	for (i = 1; i <= n; i++)
	{
	    bool found = false;
	    char c = word[i-1]; /* c = word_i_i */
	    
	    /* We're searching for a rule of the form X -> c into G */
	    gdsl_list_cursor_t cg = gdsl_list_cursor_alloc (G);
	    for (gdsl_list_cursor_move_to_head (cg); gdsl_list_cursor_get_content (cg); gdsl_list_cursor_step_forward (cg))
	    {
		rule* r = (rule*) gdsl_list_cursor_get_content (cg);
		gdsl_list_t l;
		symbol *C, *sr = rule_get_symbol (r);
		char* nom_c;
		
		if (symbol_names_compare (X, sr) != 0) continue;
		
		l = rule_get_production (r);
		if (gdsl_list_get_size (l) != 1) continue;
		
		C = (symbol*) gdsl_list_get_head (l);
		nom_c = symbol_get_name (C);
		if (strlen (nom_c) != 1) continue;
		
		if (c == nom_c[0])
		{
		    found = true;
		    break;
		}
	    }
	    gdsl_list_cursor_free (cg);
	    
	    if (found)
	    {
		gdsl_2darray_set_content (M[i], i, symbol_get_num (X), (void*) &True);
	    }
	}
    }

    /*************************************************************/
    /* CYK ALGORITHM                                             */
    /*************************************************************/
    
    for (k = 2; k <= n; k++)
    {
	for (i = k - 1; i > 0; i--)
	{
	    /* For each rule of kind X -> Y Z */
	    gdsl_list_cursor_t cg = gdsl_list_cursor_alloc (G);
	    for (gdsl_list_cursor_move_to_head (cg); gdsl_list_cursor_get_content (cg); gdsl_list_cursor_step_forward (cg))
	    {
		rule* r = (rule*) gdsl_list_cursor_get_content (cg);
		symbol* X = rule_get_symbol (r), *Y, *Z;
		gdsl_list_t l = rule_get_production (r);
		
		if (gdsl_list_get_size (l) != 2)
		{
		    continue;
		}
		
		Y = gdsl_list_get_head (l);
		Z = gdsl_list_get_tail (l);
		
		for (j = i; j <= k - 1; j++)
		{
		    int* n1;
		    int* n2;
		    gdsl_2darray_t m1 = M[i];
		    gdsl_2darray_t m2 = M[j+1];
		    n1 = (int*) gdsl_2darray_get_content (m1, j, symbol_get_num (Y));
		    n2 = (int*) gdsl_2darray_get_content (m2, k, symbol_get_num (Z));
		    
		    if (*n1 && *n2)
		    {
			gdsl_2darray_set_content (m1, k, symbol_get_num (X), (void*) &True);
		    }
		}
	    }
	}
    }
    
    {
	int* r = (int*) gdsl_2darray_get_content (M[1], n, symbol_get_num (Axiom));
	result = (*r == 1 ? true : false);
    }
    
    for (i = 1; i <= n; i++) gdsl_2darray_free (M[i]);    
    free (M);
    
    return result;
}

static void transitive_closure (void)
{
    unsigned long int i, j, k, m = gdsl_list_get_size (V);
    int zero = 0, un = 1;
    gdsl_2darray_t M = gdsl_2darray_alloc (NULL, m+1, m+1, number_alloc, number_free);
    gdsl_list_cursor_t cg;
    
    T = gdsl_2darray_alloc (NULL, m+1, m+1, number_alloc, number_free);
    
    /* Init M et T */
    for (i = 1; i <= m; i++)
    {
	for (j = 1; j <= m; j++)
	{
	    if (i == j)
	    {
		gdsl_2darray_set_content (M, i, j, (void*) &un);
		gdsl_2darray_set_content (T, i, j, (void*) &un);
	    }
	    else
	    {
		gdsl_2darray_set_content (M, i, j, (void*) &zero);
		gdsl_2darray_set_content (T, i, j, (void*) &zero);
	    }
	}
    }
    
    /* Construction des matrices M et T à partir de la grammaire G */
    cg = gdsl_list_cursor_alloc (G);
    for (gdsl_list_cursor_move_to_head (cg); gdsl_list_cursor_get_content (cg); gdsl_list_cursor_step_forward (cg))
    {
	rule* r = (rule*) gdsl_list_cursor_get_content (cg);
	gdsl_list_t l = rule_get_production (r);
	symbol* s1 = rule_get_symbol (r);
	symbol* s2;
	
	if (gdsl_list_get_size (l) != 1)
	{
	    continue;
	}
	
	s2 = (symbol*) gdsl_list_get_head (l);
	
	if (symbol_is_terminal (s2))
	{
	    continue;
	}
	
	gdsl_2darray_set_content (M, symbol_get_num (s1), symbol_get_num (s2), (void*) &un);
	gdsl_2darray_set_content (T, symbol_get_num (s1), symbol_get_num (s2), (void*) &un); 
    }
    gdsl_list_cursor_free (cg);
    
    /* Fermeture transitive (Warshall) */
    for (i = 1; i <= m; i++)
    {
	for (j = 1; j <= m; j++)
	{
	    int* z = (int*) gdsl_2darray_get_content (T, j, i);
	    
	    if (*z == 1)
	    {
		for (k = 1; k <= m; k++)
		{
		    int* a = (int*) gdsl_2darray_get_content (T, i, k);
		    if (*a == 1)
		    {
			gdsl_2darray_set_content (T, j, k, (void*) &un);
		    }
		}
	    }
	}
    }
    
    gdsl_2darray_free (M);
}

static bool leads_to (symbol* v0, symbol* v1)
{
    int* k = (int*) gdsl_2darray_get_content (T, symbol_get_num (v0), symbol_get_num (v1));
    return (*k > 0) ? true : false;
}

static void remove_useless_variables (void)
{
    symbol* s;
    gdsl_list_cursor_t cv = gdsl_list_cursor_alloc (V);
    
    gdsl_list_cursor_move_to_head (cv);
    
    while ((s = (symbol*) gdsl_list_cursor_get_content (cv)))
    {
	if (!symbol_is_in_grammar (s))
	{
	    gdsl_list_cursor_delete (cv); /* cf. NOTE 1 */
	}
	else
	{
	    gdsl_list_cursor_step_forward (cv);
	}
    }
    
    gdsl_list_cursor_free (cv);
}

static bool symbol_is_in_grammar (symbol* s)
{
    rule* r = NULL;
    gdsl_list_cursor_t cg = NULL;
    
    if (gdsl_list_search (G, symbols_compare, s) != NULL)
    {
	return true;
    }
    
    cg = gdsl_list_cursor_alloc (G);
    for (gdsl_list_cursor_move_to_head (cg); (r = (rule *) gdsl_list_cursor_get_content (cg)); gdsl_list_cursor_step_forward (cg))
    {
	gdsl_list_t ls = rule_get_production (r);
	if (gdsl_list_search (ls, strings_compare, (void *) symbol_get_name (s)) != NULL )
	{
	    gdsl_list_cursor_free (cg);
	    return true;
	}
    }
    
    gdsl_list_cursor_free (cg);
    return false;
}

static void version (void)
{
    printf ("%s version %s\n", PNAME, VERSION);
}

static void usage (void)
{
    printf ("Usage: %s -i|input-file <input file> [-o|output-file <output file>] [-h|--help] [-v|--verbose] [--version]\n", PNAME);
    printf ("       Converts the input grammar file into chomsky grammar form.\n");
    printf ("Options:\n");
    printf ("       -o|--output-file <output file>: save the chomsky grammar to file 'output file'.\n");
    printf ("       -v|--verbose: verbose mode.\n");
    printf ("       -h|--help: displays this text.\n");
    printf ("       --version: display version information.\n");
    exit (EXIT_SUCCESS);
}

/** EMACS **
 * Local variables:
 * mode: c
 * c-basic-offset: 4
 * End:
 */
